name: "yamcs-quickstart-e2e"
on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled
      - opened

jobs:
  yamcs-quickstart-e2e:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: actions/checkout@v3
        with:
          repository: unlikelyzero/quickstart
          ref: fix-network
          path: 'quickstart'
      # - name: trigger make all from docker dir. Orphan and redirect output to docker/makeout.txt
      #   run: |
      #     cd quickstart/docker
      #     touch makeout.txt
      #     make all &> makeout.txt &
      - name: trigger make all from docker dir. Orphan and redirect output to docker/makeout.txt
        run: |
          cd quickstart/docker
          docker-compose up -d
      - run: npm install
      - run: npx playwright@1.25.2 install chromium
      - run: npm run build:example
      - run: npm run test:getopensource
      - run: docker ps -a
      - run: npm run wait-for-yamcs
      - run: npm run test:e2e:quickstart
      - name: archive docker logs
        if: always()
        run: docker logs yamcs > yamcs-docker-log.txt 2>&1
      - name: archive docker logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: yamcs-docker-log.txt
      # - name: Archive makeout.txt #not working due to pathing
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     path: /quickstart/docker/makeout.txt
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: test-results
      - name: Archive html test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: tests/html-test-results
